### ISSUE TITLE
Regarding "RxPY Cohabitation with AsyncIO"

### ISSUE THREAD

**Issue by frederikaalund** [MainRo/cyclotron-py#1]
I couldn't find your e-mail address, and [the blog post in question](https://blog.oakbits.com/rxpy-and-asyncio.html) does not have a comment section, so I'm commenting here instead. Sorry about the noise. Let me know if there are better channels for this discussion.

First of all, it is a very well-written and informative blog post. Thanks for sharing your insights.

I think that I found an issue with the `to_agen` async generator. Specifically, this section:

```
while True:
    i = await queue.get()
    if isinstance(i, OnNext):
        yield i.value
        queue.task_done()
    elif isinstance(i, OnError):
        disposable.dispose()
        raise(Exception(i.value))
    else:
        disposable.dispose()
        break
```

If the async generator object is not iterated until completion, then `disposable.dispose()` is never called.

It is up to the user code to iterate the async generator object. The user can even choose to just iterate the async generator a couple of times and then discard it. In this case, a `GeneratorExit` exception will be thrown when the async generator object is garbage collected. Consequently, dispose will never be called.

This can be easily fixed by calling dispose in a finally block instead:
```
try:
    while True:
        i = await queue.get()
        if isinstance(i, OnNext):
            yield i.value
            queue.task_done()
        elif isinstance(i, OnError):
            raise(Exception(i.value))
        else:
            break
finally:
    disposable.dispose()
```

I encountered this issue in production where it led to strange errors. Thought I should let you know.

**Comment by frederikaalund** [comment]
Note that the above-mentioned solution will first dispose the observable subscription when the async generator object is garbage collected. In practice, It may take a long time before this garbage collection occurs. Consequently, the `asyncio.Queue` may needlessly fill up memory in the meantime.

In production, I use a context manager to ensure deterministic subscription cancellation (i.e., without relying solely on the garbage collector):

```
from contextlib import contextmanager

@contextmanager
def until_context_ends(observable: Observable):
	done = AsyncSubject()
	yield observable.pipe(
		ops.take_until(done),
	)
	done.on_next(None)
	done.on_completed()

@contextmanager
def to_agen(obs: Observable, *args, **kwargs):
	with until_context_ends(obs) as cm_obs:
		yield _to_agen(cm_obs, *args, **kwargs)
```

It can then be used as follows:

```
with to_agen(obs) as agen:
	async for item in agen:
		...
```

**Comment by MainRo** [comment]
Thanks for the feedback. I definitely need to add comments in the blog.
I will update the post with your ideas.

I wonder if your last example could be simplified by using aclose instead of a dedicated context manager. I did not find a equivalent of contextlib.closing for asynchronous generators, but it should be simple to write an equivalent. I suppose this would allow to directly dispose the observable from the generator without needing the until_context_ends context manager. I did not try though.

**Comment by frederikaalund** [comment]
> I wonder if your last example could be simplified by using aclose instead of a dedicated context manager. I did not find a equivalent of contextlib.closing for asynchronous generators, but it should be simple to write an equivalent. I suppose this would allow to directly dispose the observable from the generator without needing the until_context_ends context manager. I did not try though.

That could work as well. I guess that the two approaches (mine and yours) are more or less equivalent:
 1. Terminate the observable, which stops the async generator (RxPy --> async gen)
 2. Close the async generator, which cancels the subscription (async gen --> RxPy)

Seems to me that its just a matter of the order. Either will work for me. Using `aclosing` (which is indeed trivial to write) for approach 2 seems like a clean solution to me. Good suggestion.

Note that there are some [caveats with async generator's `aclose` method](https://bugs.python.org/issue38559). Said caveats won't apply for simple uses of the async generator object.

**Comment by frederikaalund** [comment]
Guess I'll just close this issue. Sorry for the noise here in the repo.
